HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

source ~/antigen.zsh

antigen use oh-my-zsh

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle rupa/z
antigen bundle git

# OSX specific
antigen bundle brew
antigen bundle brew-cask

antigen theme bureau

antigen apply

source ~/dotfiles/zsh-files/zsh_opts.zsh
source ~/dotfiles/zsh-files/exports.zsh
source ~/dotfiles/zsh-files/functions.zsh
source ~/dotfiles/zsh-files/aliases.zsh

zstyle :compinstall filename '/Users/haak/.zshrc'

autoload -Uz compinit
compinit

zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
